// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const listCards = `-- name: ListCards :many

SELECT 
    id ,
    "name" ,
    "setId" ,
    "versionId",
    "title" ,
    "cost" ,
    "type" ,
    "number" ,
    "colorMask" ,
    "illustrator" ,
    "keywords" ,
    "lore" ,
    "strength" ,
    "willpower",
    "movement" ,
    "ink" ,
    "characteristics" ,
    "abilities" ,
    "variants" ,
    "rarity" ,
    "language" ,
    "path" ,
    "franchise" ,
    "ordinal" ,
    "formats" 
FROM cards
`

// Queries.sql
func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SetId,
			&i.VersionId,
			&i.Title,
			&i.Cost,
			&i.Type,
			&i.Number,
			&i.ColorMask,
			&i.Illustrator,
			&i.Keywords,
			&i.Lore,
			&i.Strength,
			&i.Willpower,
			&i.Movement,
			&i.Ink,
			&i.Characteristics,
			&i.Abilities,
			&i.Variants,
			&i.Rarity,
			&i.Language,
			&i.Path,
			&i.Franchise,
			&i.Ordinal,
			&i.Formats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
