// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Card struct {
	ID              string
	Name            string
	SetId           string
	VersionId       int64
	Title           sql.NullString
	Cost            int64
	Type            string
	Number          string
	ColorMask       int64
	Illustrator     sql.NullString
	Keywords        sql.NullString
	Lore            sql.NullInt64
	Strength        sql.NullInt64
	Willpower       sql.NullInt64
	Movement        sql.NullInt64
	Ink             int64
	Characteristics string
	Abilities       sql.NullString
	Variants        string
	Rarity          sql.NullString
	Language        string
	Path            sql.NullString
	Franchise       sql.NullString
	Ordinal         int64
	Formats         sql.NullString
}
