services:
  db:
    image: mongo
    restart: always
    ports:
      - 9999:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch_local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Désactive l'authentification pour le dev local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limite la RAM (ajuste selon tes besoins)
    ports:
      - "9200:9200" # Port de l'API REST
      - "9300:9300" # Port de communication entre nœuds
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - lorcana_network

volumes:
  es_data:
    driver: local

networks:
  lorcana_network:
    driver: bridge

